#ifndef MYOS_SYSCALL_NUMBERS_H
#define MYOS_SYSCALL_NUMBERS_H

#define MYOS_SYSCALL_WRITE 1
#define MYOS_SYSCALL_EXIT 2
#define MYOS_SYSCALL_YIELD 3
#define MYOS_SYSCALL_UPTIME 4
#define MYOS_SYSCALL_OPEN 5
#define MYOS_SYSCALL_READ 6
#define MYOS_SYSCALL_CLOSE 7
#define MYOS_SYSCALL_GETPID 8
#define MYOS_SYSCALL_WAITPID 9
#define MYOS_SYSCALL_WRITEFILE 10
#define MYOS_SYSCALL_GUI_OPEN 11

#define MYOS_GUI_APP_TERMINAL 1
#define MYOS_GUI_APP_FILES 2
#define MYOS_GUI_APP_MONITOR 3
#define MYOS_GUI_APP_ABOUT 4
#define MYOS_GUI_APP_NOTEPAD 5

#endif
